// <auto-generated />
namespace MEGATECH.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Table0339 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Table0339));
        
        string IMigrationMetadata.Id
        {
            get { return "202405170839165_Table0339"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
