// <auto-generated />
namespace MEGATECH.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class PMH_CV : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(PMH_CV));
        
        string IMigrationMetadata.Id
        {
            get { return "202405170844592_PMH_CV"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
